import type { Metadata } from "next";

import "./globals.css";
import { morabba } from "./utils/local_font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${morabba.variable} ${morabba.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
